table building_costs
	lineageTag: 5bc8f493-1a82-432f-a18d-28a86e41419e

	column building
		dataType: string
		lineageTag: fddd22bf-9797-4eda-af19-7aeafe72cd8d
		summarizeBy: none
		sourceColumn: building

		annotation SummarizationSetBy = Automatic

	column cost
		dataType: int64
		formatString: 0
		lineageTag: 2d0621c5-55e5-45b8-b306-7c1c855f55ff
		summarizeBy: sum
		sourceColumn: cost

		annotation SummarizationSetBy = User

	partition building_costs = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents(Root & "\building_costs.csv"),[Delimiter=",", Columns=2, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"building", type text}, {"cost", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

