table markets
	lineageTag: 08b2da15-2871-4895-a9e4-afd1340d61cb

	column id
		dataType: int64
		formatString: 0
		lineageTag: 666bdf1b-8e31-48fa-ace9-97fc25595a93
		summarizeBy: none
		sourceColumn: id

		annotation SummarizationSetBy = Automatic

	column owner
		dataType: int64
		formatString: 0
		lineageTag: 4364d008-2633-409b-8e07-610a06e56047
		summarizeBy: none
		sourceColumn: owner

		annotation SummarizationSetBy = Automatic

	partition markets = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents(Root & "\markets.csv"),[Delimiter=",", Columns=2, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"id", Int64.Type}, {"owner", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

